base:
  project: iris_project
  random_state: 42
  target_col: Class_labels

data_source:
  data_path: data_given/iris.data
  columns: ['Sepal length', 'Sepal width', 'Petal length', 'Petal width', 'Class_labels']

load_data:
  raw_data: data/raw/iris.data

split_data:
  train_path: data/processed/train.data
  test_path: data/processed/test.data
  test_size: 0.25

model_dir: saved_models
webapp_model_dir: prediction_service/model/model.pkl

mlflow_config:
  artifacts_dir: artifacts
  experiment_name: IRIS-Classification
  tracking_uri: http://localhost:1234/
  run_name: mlops
  registered_model_name: SVCModel