base:
  project: iris_project
  random_state: 42
  target_col: Class_labels

data_source:
  data_path: data_given/iris.data
  columns: ['Sepal length', 'Sepal width', 'Petal length', 'Petal width', 'Class_labels']

raw_data_config:
  raw_data: data/raw/iris.data
  new_raw_data: data/raw/iris_new.csv
  target: Class_labels

processed_data_config:
  train_path: data/processed/train.data
  test_path: data/processed/test.data
  test_size: 0.25

model_dir: saved_models/model.joblib
webapp_model_dir: prediction_service/model/model.joblib

mlflow_config:
  artifacts_dir: artifacts
  experiment_name: IRIS-Classification
  tracking_uri: http://localhost:1234/
  run_name: mlops
  registered_model_name: SVCModel

model_monitor:
  target_col_name: target
  monitor_dashboard_html: reports/data_and_target_drift_dashboard.html